import React from 'react';
import { Box, Typography, Paper, Divider, List, ListItem, ListItemText } from '@mui/material';
import { KeyPointsAIResponse } from '../../../../services/AiActions/book-actions/keypoints/types';

interface KeyPointsRendererProps {
  result: KeyPointsAIResponse;
}

/**
 * Renders the result of a book key points AI action
 */
export const KeyPointsRenderer: React.FC<KeyPointsRendererProps> = ({ result }) => {
  if (!result || !result.keyPoints || result.keyPoints.length === 0) {
    return (
      <Box sx={{ mt: 2 }}>
        <Typography variant="body1">No key points available.</Typography>
      </Box>
    );
  }

  return (
    <Paper elevation={0} sx={{ p: { xs: 0, sm: 3 }, mt: 2, bgcolor: 'background.default' }}>
      <Typography variant="h6" component="h3" gutterBottom>
        Key Points
      </Typography>
      <Divider sx={{ mb: 2 }} />
      
      {/* Key points list */}
      <List dense>
        {result.keyPoints.map((point, index) => (
          <ListItem key={index}>
            <ListItemText 
              primary={point}
              primaryTypographyProps={{
                variant: 'body1',
                sx: { fontWeight: 'medium' }
              }}
            />
          </ListItem>
        ))}
      </List>
      
      <Box sx={{ mt: 3, display: 'flex', justifyContent: 'flex-end' }}>
        <Typography variant="caption" color="text.secondary">
          Generated by AI
        </Typography>
      </Box>
    </Paper>
  );
}; 