import React, { useState } from 'react';
import { 
  Box, 
  Typography, 
  Paper, 
  Divider, 
  List, 
  ListItem, 
  ListItemText, 
  IconButton,
  Collapse
} from '@mui/material';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import ExpandLessIcon from '@mui/icons-material/ExpandLess';
import { KeyPointsAIResponse } from '../../../../services/AiActions/book-actions/keypoints/types';

interface KeyPointsRendererProps {
  result: KeyPointsAIResponse;
}

/**
 * Renders the result of a book key points AI action with expandable descriptions
 */
export const KeyPointsRenderer: React.FC<KeyPointsRendererProps> = ({ result }) => {
  const [expandedItems, setExpandedItems] = useState<Record<number, boolean>>({});

  if (!result || !result.keyPoints || result.keyPoints.length === 0) {
    return (
      <Box sx={{ mt: 2 }}>
        <Typography variant="body1">No key points available.</Typography>
      </Box>
    );
  }

  const toggleExpand = (index: number) => {
    setExpandedItems(prev => ({
      ...prev,
      [index]: !prev[index]
    }));
  };

  return (
    <Paper elevation={0} sx={{ p: { xs: 0, sm: 3 }, mt: 2, bgcolor: 'background.default' }}>
      <Typography variant="h6" component="h3" gutterBottom>
        Key Points
      </Typography>
      <Divider sx={{ mb: 2 }} />
      
      {/* Key points list */}
      <List>
        {result.keyPoints.map((point, index) => (
          <React.Fragment key={index}>
            <ListItem 
              alignItems="flex-start"
              secondaryAction={
                <IconButton 
                  edge="end" 
                  onClick={() => toggleExpand(index)}
                  aria-expanded={expandedItems[index]}
                  aria-label="show more"
                >
                  {expandedItems[index] ? <ExpandLessIcon /> : <ExpandMoreIcon />}
                </IconButton>
              }
              sx={{
                cursor: 'pointer',
                '&:hover': {
                  bgcolor: 'action.hover'
                }
              }}
              onClick={() => toggleExpand(index)}
            >
              <ListItemText
                primary={
                  <Typography variant="subtitle1" sx={{ fontWeight: 'medium' }}>
                    {point.emoji} {point.title}
                  </Typography>
                }
              />
            </ListItem>
            <Collapse in={expandedItems[index]} timeout="auto" unmountOnExit>
              <Box sx={{ px: 3, pb: 2 }}>
                <Typography variant="body2" color="text.secondary">
                  {point.description}
                </Typography>
              </Box>
            </Collapse>
            {index < result.keyPoints.length - 1 && <Divider component="li" />}
          </React.Fragment>
        ))}
      </List>
      
      <Box sx={{ mt: 3, display: 'flex', justifyContent: 'flex-end' }}>
        <Typography variant="caption" color="text.secondary">
          Generated by AI
        </Typography>
      </Box>
    </Paper>
  );
}; 